version: 0.3.0.{build}
configuration: Release
platform: Any CPU
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
